title: boookk
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: # "/flexible-jekyll" # the subpath of your site, e.g. /blog
# url: "https://boookk.github.io"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: BOGYEONG KANG
author-img: profile.JPG
about-author: I'm an engineering student.
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-instagram: b_o_kk
social-github: boookk
# social-linkedin: # add your Linkedin handle
social-email: mint48579@gmail.com

# Disqus
discus-identifier: boookk # add your discus identifier

# Tracker
analytics: Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-linkpreview
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
